---
- name: Tomcat Installation
  become: yes
  hosts: all
  tasks:
    - name: Install Java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        name: tomcat
        group: tomcat
        create_home: yes
        home: /opt/tomcat
        shell: /bin/false
        state: present